# Generated by Django 4.1.7 on 2023-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('Купля-Продажа', (('b', 'Куплю'), ('s', 'Продам'))), ('Обмен', (('c', 'Обменяю'),))], default='s', max_length=1),
        ),
        migrations.AddField(
            model_name='bb',
            name='types_of_product',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип продукта'), ('new', 'Новый'), ('old', 'Б/У')], max_length=3),
        ),
    ]
