# Generated by Django 4.1.7 on 2023-03-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('r', 'Rent')], default='s', max_length=1, verbose_name='Тип объявления'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='types_of_product',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип продукта'), ('new', 'Новый'), ('old', 'Б/У')], max_length=3, verbose_name='Состояние продукта'),
        ),
    ]
