# Generated by Django 4.1.7 on 2023-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bb_kind_alter_bb_types_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите тип публикуемого объявления'), (1, 'Куплю'), (2, 'Продам'), (3, 'Обменяю'), (4, 'Rent')], default=2, max_length=1, verbose_name='Тип объявления'),
        ),
    ]
